name: Adjutor API Test Pipeline

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Newman HTML Extra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Create Reports Folder
        run: mkdir -p reports

      - name: Inject Environment Variables
        run: |
          echo "baseUrl=https://adjutor.lendsqr.com/v2" >> $GITHUB_ENV
          echo "modelId=2355" >> $GITHUB_ENV
          echo "bearerToken=${{ secrets.BEARER_TOKEN }}" >> $GITHUB_ENV

      - name: Run Newman API Tests
        run: |
          npx newman run collections/Adjutor_Decisioning_API_Test_Suite.postman_collection.json \
          --env-var "baseUrl=$baseUrl" \
          --env-var "modelId=$modelId" \
          --env-var "bearerToken=$bearerToken" \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export reports/report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: reports/